# Fonts
font_family         JetBrains Mono
font_size           16
bold_font           auto
italic_font         auto
bold_italic_font    auto
disable_ligatures   never

# Theme
include Catppuccin-Macchiato.conf

# Appearance
hide_window_decorations titlebar-only
window_padding_width 15
background_opacity 0.95
background_blur 20

# Tab bar
tab_bar_edge bottom
tab_bar_align left
tab_bar_style powerline
tab_powerline_style slanted

# OS specific tweaks
macos_option_as_alt both
# Map cmd+s to ctrl+s for consistency on macOS
map cmd+s send_text all \x13
