#!/usr/bin/env bash

wallpaper_dir="$HOME/Pictures/Wallpapers"
wallpaper=$(cd $wallpaper_dir && fd -e png -e jpg . | fuzzel -d -p "Wallpaper: ")
[ -z "$wallpaper" ] && exit 0

pkill swaybg && swaybg -i "${wallpaper_dir}/${wallpaper}"

if pgrep -x "hyprpaper" > /dev/null; then
    hyprctl hyprpaper unload
    hyprctl hyprpaper preload "${wallpaper_dir}/${wallpaper}"
    hyprctl hyprpaper wallpaper ", ${wallpaper_dir}/${wallpaper}"
elif pgrep -x "swaybg" > /dev/null || command -v swaybg > /dev/null; then
    pkill swaybg && swaybg -i "${wallpaper_dir}/${wallpaper}"
else
    exit 1
fi
