require("core.options")
require("plugins-setup")
require("core.keymaps")
require("core.colorscheme")

-- require("plugins.plugins")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.nvim-cmp")
require("plugins.comment")
require("plugins.surround")
require("plugins.autopairs")
require("plugins.lsp.mason")
require("plugins.lsp.lspconfig")
require("plugins.lsp.null-ls")
require("plugins.gitsigns")
