require("core.options")
require("plugins-setup")
require("core.keymaps")
require("core.colorscheme")

require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.nvim-cmp")
require("plugins.autopairs")
require("plugins.mason.mason")
require("plugins.mason.lspconfig")
require("plugins.mason.null-ls")
require("plugins.mason.dap")
require("plugins.gitsigns")
require("plugins.toggleterm")
require("plugins.leap")
