-- Highlight what was yanked for a short period of time
vim.api.nvim_create_autocmd("TextYankPost", {
	desc = "Highlight what was yanked",
	group = vim.api.nvim_create_augroup("UserHighlightYanked", { clear = true }),
	callback = function()
		vim.highlight.on_yank()
	end,
})

-- TypstCompile: Compile the current file with Typst
vim.api.nvim_create_user_command("TypstCompile", function()
	local filepath = vim.fn.expand("%")
	local result = vim.system({ "typst", "compile", filepath }, { text = true }):wait()

	if string.len(result.stderr) > 0 then
		vim.api.nvim_err_writeln("Typst Compile Error:\n" .. result.stderr)
	end
end, {})

-- TypstWatchStart: Start watching the current file and auto recompile it with Typst
vim.api.nvim_create_user_command("TypstWatchStart", function()
	local filepath = vim.fn.expand("%")

	if typst_watch_obj then
		vim.print("Already watching file with Typst")
		return
	end

	typst_watch_obj = vim.system({ "typst", "watch", filepath }, { text = true, detach = true }, function(obj)
		if string.len(obj.stderr) > 0 then
			vim.print("Typst Watch Error:\n" .. obj.stderr)
		end
		typst_watch_obj = nil
	end)
	vim.print("Start watching file with Typst")
end, {})

-- TypstWatchStop: Stop watching the current file
vim.api.nvim_create_user_command("TypstWatchStop", function()
	if typst_watch_obj then
		typst_watch_obj:kill(15)
		typst_watch_obj = nil
		vim.print("Stopped watching file with Typst")
	end
end, {})

-- TypstPreview: Preview the PDF file generated by Typst
vim.api.nvim_create_user_command("TypstPreview", function()
	local filepath = vim.fn.expand("%:r") .. ".pdf"

	local os = vim.loop.os_uname().sysname
	if os == "Darwin" then
		vim.system({ "open", filepath })
	else
		vim.system({ "xdg-open", filepath })
	end
end, {})

-- TypstPreviewZathura: Preview the PDF file generated by Typst with Zathura
vim.api.nvim_create_user_command("TypstPreviewZathura", function()
	local filepath = vim.fn.expand("%:r") .. ".pdf"
	vim.system({ "zathura", filepath })
end, {})
