# Global options
set -g mouse on
set -g mode-keys vi
set -g escape-time 0
set -g history-limit 10000
set -g display-time 4000
set -g focus-events on
set -g default-terminal "tmux-256color"

# Reload tmux configuration
bind R source-file "~/.tmux.conf"

# Split window horizontally
unbind %
bind | split-window -h

# Split window vertically
unbind '"'
bind - split-window -v

# List of plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin 'catppuccin/tmux'

# Plugin settings
set -g @continuum-restore "on"
set -g @catppuccin_flavour "macchiato" # latte, frappe, macchiato, mocha

# Initialize tmux plugin manager
run "~/.tmux/plugins/tpm/tpm"
