# Install all the CLI tools
cli-install:
    # Alternative to `cd`, `ls`, `cat`, `du`, `ps` and `top`
    sudo pacman -S zoxide eza bat dust procs bottom
    # Alternative to `grep`, `find`, `sed` and `diff`
    sudo pacman -S ripgrep fd sd git-delta
    # Git tools
    sudo pacman -S git gitui 
    # Image and video tools
    sudo pacman -S imagemagick ffmpeg
    # File browser
    sudo pacman -S yazi
    # Other tools
    sudo pacman -S wget less fzf just watchexec tealdeer grex tokei hyperfine pastel

# Install all the GUI applications
app-install:
    # Web browser
    sudo pacman -S firefox

# Install and setup OpenSSH
ssh-install-setup:
    # Install OpenSSH
    sudo pacman -S openssh
    # Generate SSH key
    read -p "SSH key comment: " comment; ssh-keygen -t rsa -C "$comment"
    # Start and enable the SSH service
    sudo systemctl enable --now sshd
