# Install all the CLI/TUI tools
cli-install:
    # Alternative to `cd`, `ls`, `cat`, `du`, `ps` and `top`
    sudo pacman -S zoxide eza bat dust procs bottom
    # Alternative to `grep`, `find`, `sed` and `diff`
    sudo pacman -S ripgrep fd sd git-delta
    # Git tools
    sudo pacman -S git gitui 
    # Archiving and compression tools
    sudo pacman -S zip unzip tar zstd xz gzip
    # Image and video tools
    sudo pacman -S imagemagick ffmpeg
    # File browser
    sudo pacman -S yazi
    # Man page
    sudo pacman -S man-db
    # Other tools
    sudo pacman -S fastfetch wget less fzf just watchexec jq
    sudo pacman -S tealdeer grex tokei hyperfine pastel 

# Install all the GUI/TUI applications
app-install:
    # Web browser
    sudo pacman -S firefox
    # Screenshot tools
    paru -S grim slurp grimblast-git
    # Screen recorder
    sudo pacman -S obs-studio
    # Image and video viewer
    sudo pacman -S imv mpv
    # Image editor
    sudo pacman -S gimp
    # WeChat
    paru -S wechat
    # Music player
    sudo pacman -S go-musicfox
    # Text editor
    sudo pacman -S zed

# Install and setup OpenSSH
ssh-install-setup:
    # Install OpenSSH
    sudo pacman -S openssh
    # Generate SSH key
    read -p "SSH key comment: " comment; ssh-keygen -t rsa -C "$comment"
    # Start and enable the SSH service
    sudo systemctl enable --now sshd

# Install and setup all the system tools
system-tools-install-setup:
    # Clipboard manager
    sudo pacman -S cliphist
    # Backlight control
    sudo pacman -S brightnessctl
    # Auto mount tool
    sudo pacman -S udisks2 udiskie
    # Media player control
    sudo pacman -S playerctl
    # Bluetooth
    sudo pacman -S bluez bluez-utils
    sudo systemctl enable --now bluetooth
    # Cron
    sudo pacman -S cronie
    sudo systemctl enable --now cronie

# Install all the development environments
dev-install:
    # Rust
    sudo pacman -S rustup
    # Python
    sudo pacman -S python uv

# Install catppuccin theme for GRUB
grub-theme-install:
    cd ~/Downloads && git clone https://github.com/catppuccin/grub.git catppuccin-grub && sudo cp -r catppuccin-grub/src/* /usr/share/grub/themes/
    sudo sed -i '/^#GRUB_THEME=/a GRUB_THEME="/usr/share/grub/themes/catppuccin-macchiato-grub-theme/theme.txt"' /etc/default/grub
    sudo grub-mkconfig -o /boot/grub/grub.cfg

